### ISSUE TITLE
Add duplicate Document @ IndexerService

### ISSUE THREAD

**Issue by aanciaes** [aanciaes/sd-project16-17#12]
Adding a duplicate document must return some error somehow.

**Comment by rmamaral** [comment]
He's already doing system out with the error message when you add a duplicated document!

**Comment by aanciaes** [comment]
An error code must return to the client: http code 409 Conflict

**Comment by aanciaes** [comment]
adding this block of code will do that:

```Java
if (!status)
  throw new WebApplicationException( CONFLICT );
```
