### ISSUE TITLE
DELETE action on RendezVous

### ISSUE THREAD

**Issue by aanciaes** [aanciaes/sd-project16-17#7]
Who performs the delete action on the rendezvous Server?

Is it the rendezvous server itself when it realizes that the indexer service is down?

Can an indexer service call delete before going down? (Expected Shutdown)

**Comment by rmamaral** [comment]
Rendezvous performs the delete action when an indexer service doesn't respond to the keep alive message 3 times in row. How could indexer service know that he was going down? (e.g. if the PC host of the server just went out of power?)
